### ISSUE TITLE
Plugin doesn't work with leaflet 1.1.0 and above

### ISSUE THREAD

**Issue by konstantin-belov** [Estimap/Spectrum4Leaflet#6]
Hello,

I faced a problem when I tried to use plugin with leaflet 1.1.0, 1.2.0. Tiles are loaded once at startup and then it doesn't work when I try to pan or zoom. Is it my local problem or plugin doesn't support these versions?

**Comment by SVoyt** [comment]
Yeah, I have found this behaviour too. I will try to fix it.
